
val urduStrings = Strings(
    "${UnicodeChars.MEMO} <b>جواب:</b>\n\n",
    "اس ترتیب سے خون آیا اور پاکی ملی:\n\n",
    "مبتداہ کو اس ترتیب سے خون آیا اور پاکی ملی:\n\n",
    "جب بھی خون یا دھبے آئیں تو وقت تاریخ مہینہ نوٹ فرمالیجئے۔\n\n",
    "<b>واللہ تعالی اعلم بالصواب</b>\n\n",
    "فی الحال آپ کے پاکی کے دن ہیں اپنی عبادات جاری رکھیں۔\n\n",
    "فی الحال آپ کے حیض کے دن ہیں۔ خون جاری رہنے کی صورت میں عبادات سے رک جائیں۔\n\n",
    "اگر خون ${Rplc.DT1} سے پہلے بند ہو گیا اور پندرہ دن کی کامل پاکی مل گیٔ جس میں خون اور دھبے نہیں پڑے تب پھر <b>مسلہ ضرور دوبارہ پوچھ لیں، اس لیے کہ مسئلے کی صورت بدل جائے گی۔</b>\n\n",
    "اگر خون اسی طرح جاری رہے یا فی الحال بند ہوجائے لیکن پندرہ دن کی کامل پاکی نہیں ملی کہ دوبارہ خون یا دھبہ آگیا تب پھر <b>${Rplc.DT1} کو ضرور دوبارہ پوچھ لیں، اس لیے کہ مسئلہ کی صورت بدل جائے گی۔</b>\n\n",
    "اگر ${Rplc.DT1} تک بھی خون جاری ہی رہے  تب بھی <b>${Rplc.DT1} کو غسل کر کے اپنی عبادات شروع کر دیں۔</b>\n\n",
    "حمل سے پہلے اس ترتیب سے خون آیا اور پاکی ملی:\n\n",
    "\n<b>حمل</b>\n",
    "\n<b>ولادت ${Rplc.DT1}</b>\n",
    "\n<b>ولادت کے بعد اس ترتیب سے خون آیااور پاکی ملی:</b>\n",
    "\n<b>${Rplc.DT1} کو اسقاط ہوا غیر مستبین الخلقہ (یعنی بچے کا کوئی عضو نہیں بنا)۔</b>\n",
    "اگر خون ${Rplc.DT1} سے پہلے بند ہو جاۓ تو غسل کر کے نمازیں شروع کر لیں، لیکن احتیاطا ${Rplc.DT1} کو بھی غسل کر لیجیے۔\n\n",
    "اگر سائلہ شادی شدہ ہیں تو یہ مسئلہ بھی مدنظر رکھیں: \n \n\nاگر خون رک بھي جاۓ اور غسل کر کے نمازيں بھي شروع کر لي ہوں، تب بھي ${Rplc.DT1} سے پہلے صحبت کي اجازت نہيں۔\n\n",
    "اگر خون اسی طرح جاری رہے یا فی الحال بند ہوجائے لیکن پندرہ دن کی کامل پاکی نہیں ملی کہ دوبارہ خون یا دھبہ آگیا تب پھر <b>${Rplc.DT1} تک آپ کے یقینی پاکی کے دن ہوں گے۔</b>\n\n",
    "${UnicodeChars.SNOWFLAKE} <b>عادت: حیض: ${Rplc.DUR1}، پاکی: ${Rplc.DUR2}</b>\n\n",
    "${Rplc.DT1} تا ${Rplc.DT2} کل ${Rplc.DUR1} حیض کے ہیں۔\n\n",
    "${Rplc.DT1} تا ${Rplc.DT2} کل ${Rplc.DUR1} حیض کے ہیں۔\n\n",
    "${UnicodeChars.RED_DIAMOND} ${Rplc.DT1} تا ${Rplc.DT2} کل ${Rplc.DUR1} حیض کے ہیں۔\n\n",
    "${UnicodeChars.ORANGE_DIAMOND} ${Rplc.DT1} تا ${Rplc.DT2} کل ${Rplc.DUR1} یقینی پاکی (استحاضہ) کے ہیں۔\n\n",
    "${Rplc.DT1} تا ${Rplc.DT2} کل ${Rplc.DUR1} نفاس کے ہیں۔\n\n",
    "${UnicodeChars.RED_DIAMOND} ${Rplc.DT1} تا ${Rplc.DT2} کل ${Rplc.DUR1} نفاس کے ہیں۔\n\n",
    "\n\n${Rplc.DT1} سے ${Rplc.DT2} تک کل ${Rplc.DUR1} خون۔\n\n",
    "${UnicodeChars.HAND_WRITING} <b>مسئلہ کا حل :</b>\n\n",
    "${UnicodeChars.BLACK_SQUARE} اس دوران میں جو نمازیں حیض سمجھ کر چھوڑیں،  ان کی قضاء ضروری ہے۔\n\n",
    "${UnicodeChars.BLACK_SQUARE} ${Rplc.DT1} کو اگر غسل کر لیا تھا، تو غسل کے بعد والی نمازیں درست ہیں۔ اگر غسل نہیں کیا تھا، تو جب تک غسل نہیں کیا، اس کی نمازیں قضاء کریں۔\n\n",
    "\n\n${Rplc.DT1} سے ${Rplc.DT2} تک کل ${Rplc.DUR1} خون جاری رھا (چونکہ آپ کو دو خون کے درمیان میں 15 دن کی کامل پاکی نہیں ملی ہے اسلیئے یوں سمجھا جائے گا کہ آپ کو مسلسل خون جاری ہی رہا ہے۔)\n\n",
    "${Rplc.DUR1} پاکی۔\n\n",
    "${Rplc.DUR1} طہر فاسد۔\n\n",
    "${Rplc.DUR1} استحاضہ + ${Rplc.DUR2} پاکی = ${Rplc.DUR3} طہر فاسد۔\n\n",
    "${Rplc.DUR1} پاکی (چونکہ طہر 6 ماہ سے زیادہ ہے، اس لیے عادت میں 60 دن لیا جاۓ گا۔)\n\n",
    "${UnicodeChars.FAT_DASH}${UnicodeChars.FAT_DASH}${UnicodeChars.FAT_DASH}${UnicodeChars.FAT_DASH}\n\n",
    "اب سے  یہ معتادہ ہیں۔\n\n",
    "ابھی حیض اور پاکی کی کویٔ عادت نہیں۔\n\n",
    "حیض کی عادت ${Rplc.DUR1} ہے، البتہ ابھی پاکی کی کویٔ عادت نہیں۔\n\n",
    "زبان منتخب کریں:",
    "صرف تاریخ کے ساتھ مسئلہ حل کیجیے",
    "تاریخ اور وقت کے ساتھ مسئلہ حل کیجیے",
    "اردو",
    "English",
    "MMEnglish",
    "حیض کی عادت صحیح",
    "طہر کی عادت صحیح",
    "موجودہ طہر",
    "اگر موجودہ طہر فاسد ہے تو اس خانے میں ٹک لگائیے",
    "عادت  نفاس",
    "ابتداء حمل کی تاریخ(یعنی آخری حیض کب ختم ہوا؟)",
    "اسقاط/ وضع حمل(ولادت) کاوقت/تاریخ",
    "ابتدائے خون",
    "انتہائے خون",
    "حساب لگائیں",
    "عادت درست نہیں، عادت صحیح لکھیے!",
    "نفاس",
    "مستبين الخلقہ: ",
    "مسئلہ حل کرنے کے لیے حیض و طہر کی \"عادت صحیح\" لکھیے",
    "موجودہ طہر(حل کیے جانے والے دم سے قبل متصل طہر) کا دورانیہ(duration) لکھیے۔",
    "نفاس کی عادت لکھیے! اگر پہلا بچہ ہے تو 40 کا عدد لکھیے!",
    "Please enter password here. To request the password, please contact safarjal22@gmail.com",
    "انتباہ: یہ ایپ صرف مسائل حیض میں ماہر علمائے کرام و عالمات کے استعمال کے لیے ہے، جو مسئلہ کے حل کے لیے درکار معلومات کی باریکیوں کو سمجھتے ہوں!",
    "کس طرح حل کرنا ہے؟",
    "صرف دورانیہ کے ساتھ مسئلہ حل کیجیے",
    "دم و طہر",
    "دم",
    "طہر",
    "${Rplc.DUR1} دم\n\n",
    "${Rplc.DUR1} طہر\n\n",
    "${Rplc.DUR1} طہر فاسد\n\n",
    "${Rplc.DUR1} استحاضہ + ${Rplc.DUR2} پاکی = ${Rplc.DUR3} طہر فاسد\n\n",
    "${Rplc.DUR1} حیض\n\n",
    "${Rplc.DUR1} نفاس\n\n",
    "شروع کے ${Rplc.DUR1} استحاضہ",
    "شروع کے ${Rplc.DUR1} حیض",
    "، پھر ${Rplc.DUR1} استحاضہ",
    "، پھر ${Rplc.DUR1} حیض",
    "۔\n\n",
    "ولادت\n\n",
    "حمل\n\n",
    "شروع کے ${Rplc.DUR1} نفاس",
    "اگر خون ${Rplc.DT1} یعنی 3 دن سے پہلے رک جاتا ہے،اور پھر مکمل 15 دن کی پاکی مل گیٔ تو یہ سب استحاضہ بن جاۓ گا۔\n\n",
    "اگر خون ${Rplc.DT1} سے پہلے رک جاۓ اور پھر مکمل 15 دن کی پاکی مل گیٔ تو مسئلہ ضرور دوبارہ پوچھیے، اس لیے کے مسئلے کی صورت تبدیل ہو جاۓ گی۔\n\n",
    "اگر خون ${Rplc.DT1} یعنی 40 دن کے بعد بھی جاری رہے، یا رک جاۓ لیکن 15 دن سے کم پاکی کے بعد دوبارہ شروع ہو جاۓ تو مسئلہ دوبارہ پوچھ لیجۓ۔\n\n",
    "اگر خون ${Rplc.DT1} یعنی 10 دن کے بعد بھی جاری رہے، یا رک جاۓ لیکن 15 دن سے کم پاکی کے بعد دوبارہ شروع ہو جاۓ تو مسئلہ دوبارہ پوچھ لیجۓ۔\n\n",
    "کیا غیر مستبین الخلقہ اسقاط کے مسئلے میں حمل والا طہر عادت بن سکتا ہے؟",
    "اختلافی مسائل",
    "کیا دور کے اخیر میں عادت سے زیادہ دن حیض بن سکتے ہیں؟",
    "اگر ${Rplc.DT1} سے پہلے یا ${Rplc.DT1} کو  خون رک گیا اور 15 دن کی کامل پاکی مل گیٔ، تو یہ سب حیض شمار ہو گا اور اس دوران میں کی گئی عبادات کالعدم ہو جائیں گی۔\n\n" +
            "اور اگر ${Rplc.DT1} کے بعد بھی خون جاری رہا تو سب عبادات درست رہیں گی۔\n\n",
    "اس وقت آپ کے لیے خون دیکھتے ہی نماز چھوڑنا درست نہیں ہے۔ آپ کو چاہیے کہ ${Rplc.DT1} تک عبادات جاری رکھیں۔\n\n" +
            "آپ کے عادت کے دن ${Rplc.DT1} کو شروع ہو رہے ہیں۔ اگر خون تب تک جاری رہے تو ${Rplc.DT1} سے عبادات چھوڑ دیجیے۔\n\n",
    "${Rplc.DT1} تا ${Rplc.DT2} کل ${Rplc.DUR1} خون آیا۔ (یہ ایام قبلیہ کا مسئلہ ہے)۔\n\n",
    "مبتداہ",
    "معتادہ",
    "مسئلے کی نوعیت",
    "اگر خون جاری رہے، یا رک جاۓ لیکن 15 دن سے کم پاکی کے بعد دوبارہ شروع ہو جاۓ تو مسئلہ دوبارہ پوچھ لیجۓ۔\n\n",
    "▪️چونکہ حیض کی مدت 10 دن ہے اور 10 دن پورے ہو چکے ہیں۔لہذا غسل کر کے عبادات شروع کر دیں\n\n",
    "${UnicodeChars.SNOWFLAKE} <b>عادت: نفاس: ${Rplc.DUR3}، حیض: ${Rplc.DUR1}، طہر: ${Rplc.DUR2}</b>\n\n",
    "\n<b>اسقاط ہوا (غیر مستبین الخلقہ)</b>\n",
    "کیا ایام قبلیہ میں عبادات جاری رہیں گی؟",
    "کیا مبتداہ کے حق میں اضطراری عادت بلکل حقیقی عادت کی طرح ہے؟",
    "${UnicodeChars.SNOWFLAKE} <b>عادت: نفاس: ${Rplc.DUR1}\n\n",
    "${UnicodeChars.SNOWFLAKE} <b>عادت: نفاس: ${Rplc.DUR2}، حیض: ${Rplc.DUR1}</b>\n\n",
    "${UnicodeChars.SNOWFLAKE} <b>عادت: نفاس: ${Rplc.DUR2}، پاکی: ${Rplc.DUR1}</b>\n\n",
    "${UnicodeChars.SNOWFLAKE} <b>عادت: پاکی: ${Rplc.DUR1}\n\n",
    "سائلہ کا نام یا نمبر",
    "سوال",
    "اسقاط",
    "${Rplc.DUR1} حیض اور ${Rplc.DUR2} پاکی کی عادت تھی۔ ",
    "${Rplc.DUR1} کے طہر فاسد کے بعد:\n\n",
    "ضالة",
    "Cycle Length",
    "Daylight Savings",
    "آئی ڈی سے مسلہ لوڈ کریں۔",
//    TODO:
    "Username",
    "Password",
    "Submit",
    "Log Out",
    "",
    "",
    "",
    ""
    "\n\nIt seems that your login has expired. Please log out and log in again to save the maslas in your own name."
    )
val englishStrings = Strings(
    "${UnicodeChars.MEMO} <b>Answer:</b>\n\n",
    "The bleeding and purity (tuh’r) has been in the following sequence:\n\n",
    "The bleeding and purity (tuh’r) has been in the following " +
            "sequence for the menstruation beginner:\n\n",
    "Kindly, keep note of the bleeding/spotting with month, date and time.\n\n",
    "<b>And Allah Ta’ala knows best.</b>\n\n",
    "You are in the days of your purity (tuh’r) right now, so keep up your ritual " +
            "worship as usual.\n\n",
    "You are in the days of your period right now, so, if bleeding continues you" +
            " cannot do any of your ritual worship.\n\n",
    "In case this bleeding stops before ${Rplc.DT1} and there is a gap of 15 days or more of  complete " +
            "purity with no bleeding and spotting, then <b>kindly do contact us again as " +
            "the current ruling may change accordingly.</b>\n\n",
    "In case this bleeding continues without gap, or, it continues with gaps " +
            "less than 15 days at a stretch, then <b>kindly do contact us again on ${Rplc.DT1} as " +
            "the current ruling may change accordingly.</b>\n\n",
    "If bleeding continues till ${Rplc.DT1}, then you must <b>do ghusl on ${Rplc.DT1} and begin ibadaat.</b>\n\n",
    "The bleeding and purity (tuh’r) has been in the following sequence before pregnancy:\n\n",
    "\nPregnancy\n",
    "\n<b>Date of delivery: ${Rplc.DT1}</b>\n",
    "\n<b>The bleeding and purity (tuh’r) has been in the following sequence after delivery:</b>\n",
    "\n<b>Miscarriage of an undeveloped fetus confirmed on ${Rplc.DT1}</b>\n",
    "If the bleeding stops before ${Rplc.DT1} then take ghusl immediately and start saying" +
            " your prayers but take ghusl on ${Rplc.DT1} too to be on the safe side.\n\n\n",
    "If the questioner is married, then she should keep this in mind as well: \n \n\nEven if " +
            "the bleeding stops and she performs ghusl and resumes salah, intimacy with husband " +
            "remains prohibited till ${Rplc.DT1}.\n\n",
    "In case this bleeding continues without complete 15 days of purity, " +
            "then <b>until ${Rplc.DT1}, are certainly the days of purity (tuh'r)</b>\n\n",
    "${UnicodeChars.SNOWFLAKE} Habit: ${Rplc.DUR1}/${Rplc.DUR2} \n\n",
    "${Rplc.DT1} to ${Rplc.DT2}, a total of ${Rplc.DUR1} of period.\n\n",
    "${Rplc.DT1} to ${Rplc.DT2}, a total of ${Rplc.DUR1} of period.\n\n",
    "${UnicodeChars.RED_DIAMOND} ${Rplc.DT1} to ${Rplc.DT2}, a total of ${Rplc.DUR1} of period.\n\n",
    "${UnicodeChars.ORANGE_DIAMOND} ${Rplc.DT1} to ${Rplc.DT2}, a total of ${Rplc.DUR1} of definitive" +
            " purity (istehadha).\n\n",
    "${Rplc.DT1} to ${Rplc.DT2}, a total of ${Rplc.DUR1} of post-natal bleeding.\n\n",
    "${UnicodeChars.RED_DIAMOND} ${Rplc.DT1} to ${Rplc.DT2}, a total of ${Rplc.DUR1} of post-natal bleeding.\n\n",
    "\n\n${Rplc.DT1} to ${Rplc.DT2}, a total of ${Rplc.DUR1} of blood.\n\n",
    "${UnicodeChars.HAND_WRITING} <b>Solution:</b>\n\n",
    "${UnicodeChars.BLACK_SQUARE} If you left any salah thinking of it as haidh and it turned " +
            "out to be istehadha, then make qada of them.\n\n",
    "${UnicodeChars.BLACK_SQUARE} If you performed ghusl on ${Rplc.DT1}, salah after " +
            "it are all valid. If you didn't, then make qada of all the salah until you took ghusl.\n\n",
    "\n\n${Rplc.DUR1} of continued bleeding from ${Rplc.DT1} to ${Rplc.DT2} (since you haven’t had 15 " +
            "or more blood-free days at a stretch in there)\n\n",
    "${Rplc.DUR1} of purity (tuh’r)\n\n",
    "${Rplc.DUR1} of invalid purity (tuh'r-e-faasid)\n\n",
    "${Rplc.DUR1} of istehadha + ${Rplc.DUR2} of purity (tuh’r) = ${Rplc.DUR3} of invalid" +
            " purity (tuh'r-e-faasid).\n\n",
    "${Rplc.DUR1} of purity (tuh'r). (Since purity (tuh’r) is of more than 6 months, " +
            "therefore 60 days shall be taken as habit of purity (tuh’r)\n\n",
    "${UnicodeChars.FAT_DASH}${UnicodeChars.FAT_DASH}${UnicodeChars.FAT_DASH}${UnicodeChars.FAT_DASH}\n\n",
    "From now on, she is a mu'tada\n\n",
    "Till now, there is no habit of haidh or purity (tuh'r)\n\n",
    "${Rplc.DUR1} is the habit of haidh. There is no habit of purity (tuh'r) yet.\n\n",
    "Select Language",
    "Date only",
    "Date and Time",
    "اردو",
    "English",
    "MMEnglish",
    "Habit in Haidh",
    "Habit in Purity (Tuh'r)",
    "Current Purity (Tuh'r)",
    "Invalid Purity (Tuh'r e Faasid)",
    "Habit in Nifas",
    "Pregnancy Start Time",
    "Birth/Miscarriage Time",
    "Start Time",
    "End Time",
    "Calculate",
    "Habit is incorrect",
    "Nifas",
    "Mustabeen ul Khilqat",
    "Please enter habit of haidh and purity (tuh'r) to solve this",
    "Please enter a duration for Current Purity",
    "Please enter Nifas Habit to solve this. If this is a first baby, please enter 40.",
    "Please enter password here. To request the password, please contact safarjal22@gmail.com",
    "Attention!! This app is only for use by Ulema and Aalimaat " +
            "who are experts in solving the masail of haidh and nifas, and understand the " +
            "minutae of the information required to solve this.",
    "Type of input: ",
    "Duration",
    "Dam/Purity",
    "Dam",
    "Purity",
    "${Rplc.DUR1} dam\n\n",
    "${Rplc.DUR1} purity (tuh'r)\n\n",
    "${Rplc.DUR1} invalid purity (tuh'r-e-faasid)\n\n",
    "${Rplc.DUR1} of istehadha + ${Rplc.DUR2} of purity (tuh'r) = ${Rplc.DUR3} of invalid purity (tuh'r-e-faasid)\n\n",
    "${Rplc.DUR1} haidh\n\n",
    "${Rplc.DUR1} nifas\n\n",
    "The first ${Rplc.DUR1} are istehadha",
    "The first ${Rplc.DUR1} are haidh",
    ", then the next ${Rplc.DUR1} are istehadha",
    ", then the next ${Rplc.DUR1} are haidh",
    ".\n\n",
    "Birth\n\n",
    "Pregnancy\n\n",
    "The first ${Rplc.DUR1} are nifas",
    "If bleeding stops before ${Rplc.DT1} (3 days), and is followed by a 15 day" +
            " or more period of purity, then all of this will become istehadha.\n\n",
    "If bleeding stops before ${Rplc.DT1} (3 days), then please ask again, " +
            "as the masla will change.\n\n",
    "If bleeding continues after ${Rplc.DT1} (40 days), or stops, but starts again with gaps " +
            "of less than 15 days, then please ask the masla again.\n\n",
    "If bleeding continues after ${Rplc.DT1} (10 days), or stops, but starts again " +
            "with gaps of less than 15 days, then please ask the masla again.\n\n",
    "Can the purity during pregnancy be used as a habit in case" +
            " of miscarriage of an unformed foetus?",
    "Differences of opinion",
    "Can more days than habit become haidh at the end of daur?",
    "If bleeding stopped at or before ${Rplc.DT1}, and there was an" +
            " interval of at 15 days of complete purity after it, all of this will become haidh, and " +
            "ibadaat performed in this time will become null and void.\n\n" +
            "If bleeding continues past ${Rplc.DT1}, all ibadaat will remain valid.\n\n",
    "It is not correct for you to stop ibadaat when bleeding starts. You should " +
            "continue ibadaat till ${Rplc.DT1}, the start of your habit.\n\n" +
            "Your habit days are beginning from ${Rplc.DT1}. If bleeding continues till then, then you " +
            "should stop praying from ${Rplc.DT1}.\n\n",
    "${Rplc.DT1} to ${Rplc.DT2}, a total of ${Rplc.DUR1} of bleeding. (This is a case of Ayyam-e-Qabliyya).\n\n",
    "Mubtadia",
    "Mu'tada",
    "Type of Masla",
    "If bleeding continues, or stops, but starts again " +
            "with gaps of less than 15 days, then please ask the masla again.\n\n",
    "As the maximum duration for haidh is 10 days, " +
            "and it is now ten days, please do ghusl and resume your ibadat.\n\n",
    "${UnicodeChars.SNOWFLAKE} Habit: Nifas : ${Rplc.DUR3}, Haidh : ${Rplc.DUR1}, Purity (Tuh’r): ${Rplc.DUR2} \n\n",
    "\n<b>Miscarriage of an undeveloped fetus</b>\n",
    "Will ibadaat be continued during ayyam-e-qabliyya?",
    "Does iztirari habit become real habit in mubtadia?",
    "${UnicodeChars.SNOWFLAKE} Habit: Nifas : ${Rplc.DUR1} \n\n",
    "${UnicodeChars.SNOWFLAKE} Habit: Nifas : ${Rplc.DUR2}, Haidh : ${Rplc.DUR1}\n\n",
    "${UnicodeChars.SNOWFLAKE} Habit: Nifas : ${Rplc.DUR2}, Purity (Tuh'r) : ${Rplc.DUR1}\n\n",
    "${UnicodeChars.SNOWFLAKE} Habit: Purity (Tuh'r) : ${Rplc.DUR1} \n\n",
    "Name/Phone Number of Questioner",
    "Question",
    "Miscarriage",
    "Previous habit was ${Rplc.DUR1} in haidh and ${Rplc.DUR2} in purity. ",
    "After ${Rplc.DUR1} of invalid tuh'r: \n\n",
    "Zaalla",
    "Cycle Length",
    "Daylight Savings",
    "Load Masla From ID",
    "Username",
    "Password",
    "Submit",
    "Log Out",
    "",
    "",
    "",
    ""
    "\n\nIt seems that your login has expired. Please log out and log in again to save the maslas in your own name."
    )
val mmEnglishStrings = Strings(
    "In the name of Allah, the Inspirer of truth\n\n",
    "<table><tr><th>Dates</th><th>Bleeding</th><th>Subsequent Purity</th><th>Comments</th></tr>",
    "",
    "Kindly, keep note of the bleeding/spotting with month, date and time.\n\n",
    "<b>And Allah Ta’ala knows best.</b>\n\nAnswered by,\n\n",
    "You are in the days of your tuhr right now, so keep up your ritual worship as usual.\n\n",
    "You are in the days of your hayd right now, so, if bleeding continues you cannot do any of your ritual worship.\n\n",
    "If this bleeding has stopped before ${Rplc.DT1} and you get purity of complete 15 days or more, refer again for further assistance.\n\n",
    "If there is no complete purity of 15 days and the intermittent bleeding spotting continues until ${Rplc.DT1}, " +
            "please refer again as the whole masala could change.\n\n",
    "If bleeding continues till ${Rplc.DT1}, then you must <b>do ghusl on ${Rplc.DT1} and begin ibadaat.</b>\n\n",
    "The bleeding and tuhr has been in the following sequence before pregnancy:\n\n",
    "\nPregnancy\n",
    "\n<b>Date of delivery: ${Rplc.DT1}</b>\n",
    "",
    "\n<b>Miscarriage of an undeveloped fetus confirmed on ${Rplc.DT1}</b>\n",
    "If the bleeding stops before ${Rplc.DT1} then take ghusl immediately and start saying your prayers but take ghusl on ${Rplc.DT1} too to be on the safe side.\n\n\n",
    "If the questioner is married, then she should keep this in mind as well: \n \n\nEven if the bleeding stops and she performs ghusl and resumes salah, intimacy with husband remains prohibited till ${Rplc.DT1}.\n\n",
    "In case this bleeding continues without complete 15 days of purity,  then <b>until ${Rplc.DT1}, are certainly the days of tuhr</b>\n\n",
    "Habit: ${Rplc.DUR1}/${Rplc.DUR2} \n\n",
    "<tr><td>${Rplc.DT1}-${Rplc.DT2}</td> <td>${Rplc.DUR1}</td>",
    "<tr><td>${Rplc.DT1}-${Rplc.DT2}</td> <td colspan=\"2\">${Rplc.DUR1}</td>",
    "",
    "",
    "${Rplc.DT1}-${Rplc.DT2}, a total of ${Rplc.DUR1} of post-natal bleeding (nifas).\n\n",
    "${Rplc.DT1}-${Rplc.DT2}, a total of ${Rplc.DUR1} of post-natal bleeding (nifas).\n\n",
    "<tr><td>${Rplc.DT1}-${Rplc.DT2}</td><td>${Rplc.DUR1}</td>",
    "",
    "",
    "",
    "${Rplc.DT1}-${Rplc.DT2} --- ${Rplc.DUR1}",
    "<td>${Rplc.DUR1}</td>",
    "${Rplc.DUR1} of invalid purity (tuhr fasid)\n\n",
    "<td>${Rplc.DUR1} istihada + ${Rplc.DUR2} = ${Rplc.DUR3}</td>",
    "<td> Purity of more than 6 months</td>",
    "",
    "From now on, she is a mu'tada (habitual woman)\n\n",
    "Till now, there is no habit of haid or purity (tuhr)\n\n",
    "\n\nHabit:${Rplc.DUR1}/?\n\n",
    "Select Language",
    "Date only",
    "Date and Time",
    "اردو",
    "English",
    "MMEnglish",
    "Habit in Haidh",
    "Habit in Purity (Tuhr)",
    "Current Purity (Tuhr)",
    "Invalid Purity (Tuhr Fasid)",
    "Habit in Nifas",
    "Pregnancy Start Time",
    "Birth/Miscarriage Time",
    "Start Time",
    "End Time",
    "Calculate",
    "Habit is incorrect",
    "Nifas",
    "Mustabeen ul Khilqat",
    "Please enter habit of haid and purity (tuhr) to solve this",
    "Please enter a duration for Current Purity",
    "Please enter Nifas Habit to solve this. If this is a first baby, please enter 40.",
    "Please enter password here. To request the password, please contact safarjal22@gmail.com",
    "Attention!! This app is only for use by Ulema and Aalimaat who are experts in solving the masail of haid and nifas, and understand the minutiae of the information required to solve this.",
    "Type of input: ",
    "Duration",
    "Dam/Purity",
    "Dam",
    "Purity",
    "${Rplc.DUR1} dam\n\n",
    "${Rplc.DUR1} purity (tuhr)\n\n",
    "${Rplc.DUR1} invalid purity (tuhr fasid)\n\n",
    "${Rplc.DUR1} of istihada + ${Rplc.DUR2} of purity (tuhr) = ${Rplc.DUR3} of invalid purity (tuhr fasid)\n\n",
    "${Rplc.DUR1} haidh\n\n",
    "${Rplc.DUR1} nifas\n\n",
    "The first ${Rplc.DUR1} are istihada",
    "The first ${Rplc.DUR1} are haid",
    ", then the next ${Rplc.DUR1} are istihada",
    ", then the next ${Rplc.DUR1} are haid",
    ".\n\n",
    "Birth\n\n",
    "Pregnancy\n\n",
    "The first ${Rplc.DUR1} are nifas",
    "If its less than 3 days and nights, it will all be istihada.\n\n",
    "If bleeding stops before ${Rplc.DT1} (3 days), then please ask again, as the masla will change.\n\n",
    "If bleeding continues after ${Rplc.DT1} (40 days), or stops, but starts again with gaps of less than 15 days, then please ask the masla again.\n\n",
    "If bleeding continues after ${Rplc.DT1} (10 days), or stops, but starts again with gaps of less than 15 days, then please ask the masla again.\n\n",
    "Can the purity during pregnancy be used as a habit in case of miscarriage of an unformed fetus?",
    "Differences of opinion",
    "Can more days than habit become haid at the end of daur?",
    "If bleeding stopped at or before ${Rplc.DT1}, and there was an interval of at 15 days of complete purity after it, all of this will become haid, and ibadaat performed in this time will become null and void.\n\n  " +
            "If bleeding continues past ${Rplc.DT1}, all ibadaat will remain valid.\n\n",
    "It is not correct for you to stop ibadaat when bleeding starts. You should continue ibadaat till ${Rplc.DT1}, the start of your habit.\n\n " +
        "Your habit days are beginning from ${Rplc.DT1}. If bleeding continues till then, then you should stop praying from ${Rplc.DT1}.\n\n",
    "<tr><td>${Rplc.DT1}-${Rplc.DT2}</td> <td colspan = \"2\">${Rplc.DUR1}</td>",
    "Mubtadi’a",
    "Mu'tada",
    "Type of Masla",
    "If bleeding continues, or stops, but starts again with gaps of less than 15 days, then please ask the masla again.\n\n",
    "As the maximum duration for haid is 10 days, and it is now ten days, please do ghusl and resume your ibadaat.\n\n",
    "Habit: Nifas : ${Rplc.DUR3}, Haidh : ${Rplc.DUR1}, Purity (Tuhr): ${Rplc.DUR2} \n\n",
    "\n<b>Miscarriage of an undeveloped fetus</b>\n",
    "Will ibadaat be continued during ayyam-e-qabliyya?",
    "Does iztirari habit become real habit in mubtadi’a?",
    "Habit: Nifas : ${Rplc.DUR1} \n\n",
    "Habit: Nifas : ${Rplc.DUR2}, Haid : ${Rplc.DUR1}\n\n",
    "Habit: Nifas : ${Rplc.DUR2}, Purity (Tuhr) : ${Rplc.DUR1}\n\n",
    "Habit: Purity (Tuhr) : ${Rplc.DUR1} \n\n",
    "Name/Phone Number of Questioner",
    "Question",
    "Miscarriage",
    "Previous habit was ${Rplc.DUR1} in haid and ${Rplc.DUR2} in purity. ",
    "After ${Rplc.DUR1} of invalid tuhr: \n\n",
    "Mudilla",
    "Cycle Length",
    "Daylight Savings",
    "Load Masla From ID",
    "Username",
    "Password",
    "Submit",
    "Log Out",
    "</table>\n\n",
    "<td>Habit: ${Rplc.DUR1}/${Rplc.DUR2}</td></tr>",
    "</tr>",
    "<td>This is a case of Ayyam-e-Qabliyya</td></tr>",
    "\n\nIt seems that your login has expired. Please log out and log in again to save the maslas in your own name."


)


object StringsOfLanguages{
    val URDU: Strings = urduStrings
    val ENGLISH: Strings = englishStrings
    val MMENGLISH: Strings = mmEnglishStrings
}


var dtStrings = arrayOf (
    TzInfo("(GMT-08:00) US & Canada","America/Los_Angeles"),
    TzInfo("(GMT+00:00) Europe","Europe/London"),
    TzInfo("(GMT+10:00) Australia","Australia/Canberra"),
)

//var tzStrings = arrayOf <TzInfo> (
//    TzInfo("(GMT-12:00) International Date Line West","Etc/GMT+12"),
//    TzInfo("(GMT-11:00) Midway Island, Samoa","Pacific/Midway"),
//    TzInfo("(GMT-10:00) Hawaii","Pacific/Honolulu"),
//    TzInfo("(GMT-09:00) Alaska","US/Alaska"),
//    TzInfo("(GMT-08:00) Pacific Time (US & Canada)","America/Los_Angeles"),
//    TzInfo("(GMT-08:00) Tijuana, Baja California","America/Tijuana"),
//    TzInfo("(GMT-07:00) Arizona","US/Arizona"),
//    TzInfo("(GMT-07:00) Chihuahua, La Paz, Mazatlan","America/Chihuahua"),
//    TzInfo("(GMT-07:00) Mountain Time (US & Canada)","US/Mountain"),
//    TzInfo("(GMT-06:00) Central America","America/Managua"),
//    TzInfo("(GMT-06:00) Central Time (US & Canada)","US/Central"),
//    TzInfo("(GMT-06:00) Guadalajara, Mexico City, Monterrey","America/Mexico_City"),
//    TzInfo("(GMT-06:00) Saskatchewan","Canada/Saskatchewan"),
//    TzInfo("(GMT-05:00) Bogota, Lima, Quito, Rio Branco","America/Bogota"),
//    TzInfo("(GMT-05:00) Eastern Time (US & Canada)","US/Eastern"),
//    TzInfo("(GMT-05:00) Indiana (East)","US/East-Indiana"),
//    TzInfo("(GMT-04:00) Atlantic Time (Canada)","Canada/Atlantic"),
//    TzInfo("(GMT-04:00) Caracas, La Paz","America/Caracas"),
//    TzInfo("(GMT-04:00) Manaus","America/Manaus"),
//    TzInfo("(GMT-04:00) Santiago","America/Santiago"),
//    TzInfo("(GMT-03:30) Newfoundland","Canada/Newfoundland"),
//    TzInfo("(GMT-03:00) Brasilia","America/Sao_Paulo"),
//    TzInfo("(GMT-03:00) Buenos Aires, Georgetown","America/Argentina/Buenos_Aires"),
//    TzInfo("(GMT-03:00) Greenland","America/Godthab"),
//    TzInfo("(GMT-03:00) Montevideo","America/Montevideo"),
//    TzInfo("(GMT-02:00) Mid-Atlantic","America/Noronha"),
//    TzInfo("(GMT-01:00) Cape Verde Is.","Atlantic/Cape_Verde"),
//    TzInfo("(GMT-01:00) Azores","Atlantic/Azores"),
//    TzInfo("(GMT+00:00) Casablanca, Monrovia, Reykjavik","Africa/Casablanca"),
//    TzInfo("(GMT+00:00) Greenwich Mean Time : Dublin, Edinburgh, Lisbon, London","Etc/Greenwich"),
//    TzInfo("(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna","Europe/Amsterdam"),
//    TzInfo("(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague","Europe/Belgrade"),
//    TzInfo("(GMT+01:00) Brussels, Copenhagen, Madrid, Paris","Europe/Brussels"),
//    TzInfo("(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb","Europe/Sarajevo"),
//    TzInfo("(GMT+01:00) West Central Africa","Africa/Lagos"),
//    TzInfo("(GMT+02:00) Amman","Asia/Amman"),
//    TzInfo("(GMT+02:00) Athens, Bucharest, Istanbul","Europe/Athens"),
//    TzInfo("(GMT+02:00) Beirut","Asia/Beirut"),
//    TzInfo("(GMT+02:00) Cairo","Africa/Cairo"),
//    TzInfo("(GMT+02:00) Harare, Pretoria","Africa/Harare"),
//    TzInfo("(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius","Europe/Helsinki"),
//    TzInfo("(GMT+02:00) Jerusalem","Asia/Jerusalem"),
//    TzInfo("(GMT+02:00) Minsk","Europe/Minsk"),
//    TzInfo("(GMT+02:00) Windhoek","Africa/Windhoek"),
//    TzInfo("(GMT+03:00) Kuwait, Riyadh, Baghdad","Asia/Kuwait"),
//    TzInfo("(GMT+03:00) Moscow, St. Petersburg, Volgograd","Europe/Moscow"),
//    TzInfo("(GMT+03:00) Nairobi","Africa/Nairobi"),
//    TzInfo("(GMT+03:00) Tbilisi","Asia/Tbilisi"),
//    TzInfo("(GMT+03:30) Tehran","Asia/Tehran"),
//    TzInfo("(GMT+04:00) Abu Dhabi, Muscat","Asia/Muscat"),
//    TzInfo("(GMT+04:00) Baku","Asia/Baku"),
//    TzInfo("(GMT+04:00) Yerevan","Asia/Yerevan"),
//    TzInfo("(GMT+04:30) Kabul","Asia/Kabul"),
//    TzInfo("(GMT+05:00) Yekaterinburg","Asia/Yekaterinburg"),
//    TzInfo("(GMT+05:00) Islamabad, Karachi, Tashkent","Asia/Karachi"),
//    TzInfo("(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi","Asia/Calcutta"),
//    TzInfo("(GMT+05:30) Sri Jayawardenapura","Asia/Calcutta"),
//    TzInfo("(GMT+05:45) Kathmandu","Asia/Katmandu"),
//    TzInfo("(GMT+06:00) Almaty, Novosibirsk","Asia/Almaty"),
//    TzInfo("(GMT+06:00) Astana, Dhaka","Asia/Dhaka"),
//    TzInfo("(GMT+06:30) Yangon (Rangoon)","Asia/Rangoon"),
//    TzInfo("(GMT+07:00) Bangkok, Hanoi, Jakarta","Asia/Bangkok"),
//    TzInfo("(GMT+07:00) Krasnoyarsk","Asia/Krasnoyarsk"),
//    TzInfo("(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi","Asia/Hong_Kong"),
//    TzInfo("(GMT+08:00) Kuala Lumpur, Singapore","Asia/Kuala_Lumpur"),
//    TzInfo("(GMT+08:00) Irkutsk, Ulaan Bataar","Asia/Irkutsk"),
//    TzInfo("(GMT+08:00) Perth","Australia/Perth"),
//    TzInfo("(GMT+08:00) Taipei","Asia/Taipei"),
//    TzInfo("(GMT+09:00) Osaka, Sapporo, Tokyo","Asia/Tokyo"),
//    TzInfo("(GMT+09:00) Seoul","Asia/Seoul"),
//    TzInfo("(GMT+09:00) Yakutsk","Asia/Yakutsk"),
//    TzInfo("(GMT+09:30) Adelaide","Australia/Adelaide"),
//    TzInfo("(GMT+09:30) Darwin","Australia/Darwin"),
//    TzInfo("(GMT+10:00) Brisbane","Australia/Brisbane"),
//    TzInfo("(GMT+10:00) Canberra, Melbourne, Sydney","Australia/Canberra"),
//    TzInfo("(GMT+10:00) Hobart","Australia/Hobart"),
//    TzInfo("(GMT+10:00) Guam, Port Moresby","Pacific/Guam"),
//    TzInfo("(GMT+10:00) Vladivostok","Asia/Vladivostok"),
//    TzInfo("(GMT+11:00) Magadan, Solomon Is., New Caledonia","Asia/Magadan"),
//    TzInfo("(GMT+12:00) Auckland, Wellington","Pacific/Auckland"),
//    TzInfo("(GMT+12:00) Fiji, Kamchatka, Marshall Is.","Pacific/Fiji"),
//    TzInfo("(GMT+13:00) Nuku'alofa","Pacific/Tongatapu"),
//)